### PR TITLE
Class Diagram

### PR DESCRIPTION
**Pull request by hate-bug**
Here is the class diagram for this project. 
The system contains 4 classes: Event, Place, Anonymous_Patient, and Trusted_User.  
Truested_User represents institutional workers, that are allowed to create anonymous patients and input their attended events. 
Anonymous_User can be created by Trusted_Worker or input by anonymous users. 
Events are created by users and each event is associated with a place.
Place class is used to store location and address for each event.

### CODE REVIEW

**Comment by esfandia** [comment]
Looks good to me! You also need an arrow from Event to Anonymous_Patient. Anonymous_Patient needs a constructor (also remember all Entity classes will need a default constructor). I don't know if underscores are idiomatic in UML; they aren't in Java, So maybe just name them AnonymousPatient and TrustedUser? If a TrustedUser creates AnonymousPatients, does it also keep track of them and therefore has a list of them (of those that it created)? I imagine that it's still possible for anonymous (untrusted) users to create AnonymousPatients, it's just that those won't be tracked. Would also use a <<Entity>> prototype on Entity classes (all the calsses in this diagram).

**Comment by hate-bug** [comment]
@esfandia Just updated the class diagram and corresponding ORM table.

**Comment by esfandia** [comment]
I don't think you need the AnonymousUser class, and more importantly it shouldn't have a userName (it is, after all, anonymous!). TrustedUser on the other hand might be needed,  to check that when it is inputting information we know that it is verified. But maybe it is wrong to think only of the Patient as something that is verified, because even the events, places and more importantly which patient attended which event are things that need verification as well. 

It might be easier for now not to worry about the various User classes at all, as Authentication and Authorization rules (Spring Security stuff, for example) might take care of that stuff for us.

On another topic, you want the constructors to take all needed parameters, not just the name.

**Comment by esfandia** [comment]
Just need to fix the constructor parameters (Event(...) needs a date, AnonymousPatient(...) doesn't have a name, and you should be good to go. By the way, since our patients will always be anonymous, there is no need for the Anonymous prefix for the class name.

**Pull request merged**
